[bot]
owner_tg_id = 12345678
admins = [12345678]
token = "token"
drop_pending = true
use_webhook = false
use_class_middlewares = true
actions_timeout = 0.2
page_size = 10

logger.name = "BotLogger"
logger.level = "DEBUG"
logger.stream = "stdout"
logger.file_path = "logs/bot.log"
logger.format = "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

# allowed_updates = [...] or "ALL"

state_storage.type = "redis"
state_storage.redis.host = "localhost"
state_storage.redis.port = 6379
# state_storage.redis.db = 0
# state_storage.redis.password = "password"
# state_storage.redis.prefix = "prefix"

webhook.base_url = "webhook_base_url"
webhook.path = "webhook_path"
webhook.secret_token = "secret token"
# webhook.cert_path = "cert_path"
# webhook.ip_address = "ip_address"
# webhook.max_connections = 40

# telegram_api_url = "telegram_api_url"

# [extra sections if any]
# ...

[logger]
name = "BetonBotLogger"
level = "INFO"
stream = "stdout"
file_path = "logs/beton_bot.log"
format = "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

[messages]
welcome = "Вітаю!"
help = "Help message"
anti_flood = "Anti flood message"
unknown_update = "This feature is not supported yet"
unknown_error = "Unknown error"
add_tg_account_error = "Add telegram account error"

[buttons]
help = "Help"

[db]
host = ""
port = 0
user = ""
password = ""
database = ""

logger.name = "DBLogger"
logger.level = "INFO"
logger.stream = "stdout"
logger.file_path = "logs/db.log"
logger.format = "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
